# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 542da9c7f3cbc86a75cbf81ad2cef19a69965d3e911f50cedc2b724909a7fa024b265b9cbfcc4142bd6a55a5cb8bc2415a1bb57aa2b562cf57cd65943324916e

test:
  secret_key_base: ddcb012dc58e0ef27d7ec09f44a04d29e94e2c8906534d79f4686faf999c58fc31a184640c19d54d5af23ddc7dd1ac4386ec9b3ed7dd4dc910d332b5a687e874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
